/*
 * Copyright (c) Velocity BPA, LLC
 * Licensed under the Business Source License 1.1
 * Commercial use requires a separate commercial license.
 * See LICENSE file for details.
 */

/**
 * Claim Adjustment Reason Codes (CARC)
 *
 * Standard codes used to explain adjustments to healthcare claims.
 * Based on X12 835 transaction set specifications maintained by
 * Washington Publishing Company (WPC).
 */
export const CARC_CODES: Record<string, string> = {
  // Common denial/adjustment codes
  '1': 'Deductible amount',
  '2': 'Coinsurance amount',
  '3': 'Co-payment amount',
  '4': 'The procedure code is inconsistent with the modifier used or a required modifier is missing',
  '5': 'The procedure code/bill type is inconsistent with the place of service',
  '6': 'The procedure/revenue code is inconsistent with the patient\'s age',
  '7': 'The procedure/revenue code is inconsistent with the patient\'s gender',
  '8': 'The procedure code is inconsistent with the provider type/specialty',
  '9': 'The diagnosis is inconsistent with the patient\'s age',
  '10': 'The diagnosis is inconsistent with the patient\'s gender',
  '11': 'The diagnosis is inconsistent with the procedure',
  '12': 'The diagnosis is inconsistent with the provider type',
  '13': 'The date of death precedes the date of service',
  '14': 'The date of birth follows the date of service',
  '15': 'The authorization number is missing, invalid, or does not apply',
  '16': 'Claim/service lacks information or has submission/billing error(s)',
  '17': 'Requested information was not provided or was insufficient/incomplete',
  '18': 'Exact duplicate claim/service',
  '19': 'This is a work-related injury/illness and thus the liability of Workers\' Compensation',
  '20': 'This injury/illness is covered by the liability carrier',
  '21': 'This injury/illness is the liability of the no-fault carrier',
  '22': 'This care may be covered by another payer per coordination of benefits',
  '23': 'The impact of prior payer(s) adjudication including payments and/or adjustments',
  '24': 'Charges are covered under a capitation agreement/managed care plan',
  '25': 'Payment denied. Your stop loss deductible has not been met',
  '26': 'Expenses incurred prior to coverage',
  '27': 'Expenses incurred after coverage terminated',
  '28': 'Coverage not in effect at the time the service was provided',
  '29': 'The time limit for filing has expired',
  '30': 'Payment adjusted because the patient has not met the required eligibility',
  '31': 'Patient cannot be identified as our insured',
  '32': 'Our records indicate that this dependent is not an eligible dependent',
  '33': 'Insurance company denied payment for this service',
  '34': 'Insurance company denied payment - inpatient services',
  '35': 'Lifetime benefit maximum has been reached',
  '36': 'Balance does not exceed co-payment amount',
  '37': 'Balance does not exceed deductible',
  '38': 'Services not provided or authorized by designated provider',
  '39': 'Services denied at the time authorization/pre-certification was requested',
  '40': 'Charges do not meet qualifications for emergent/urgent care',
  '41': 'Discount agreed to in Preferred Provider contract',
  '42': 'Charges exceed our fee schedule or maximum allowable amount',
  '43': 'Gramm-Rudman reduction',
  '44': 'Prompt-pay discount',
  '45': 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement',
  '49': 'These are non-covered services because this is a routine/preventive exam',
  '50': 'These are non-covered services because this is not deemed a "medical necessity"',
  '51': 'These are non-covered services because this is a pre-existing condition',
  '52': 'The time limit for filing has expired per regulatory requirement',
  '53': 'Services by an immediate relative or a member of the same household are not covered',
  '54': 'Multiple physicians/assistants are not covered in this case',
  '55': 'Procedure/treatment/drug is deemed experimental/investigational',
  '56': 'Procedure/treatment has not been deemed "proven to be effective"',
  '57': 'Payment denied/reduced because the payer deems the information submitted does not support this level of service',
  '58': 'Payment adjusted because treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service',
  '59': 'Charges are adjusted based on multiple surgery rules or concurrent anesthesia rules',
  '60': 'Charges for outpatient services are not covered when performed within a period of time prior to or after inpatient services',
  '61': 'Penalty for failure to obtain second surgical opinion',
  '62': 'Payment denied/reduced for absence of, or exceeded, precertification/authorization',

  // Additional common codes
  '96': 'Non-covered charges',
  '97': 'Payment is included in the allowance for another service/procedure',
  '100': 'Payment made to patient/insured/responsible party/employer',
  '101': 'Predetermination: anticipated payment upon completion of services',
  '102': 'Major medical adjustment',
  '103': 'Provider promotional discount',
  '104': 'Managed care withholding',
  '105': 'Tax withholding',
  '106': 'Patient payment option/election not in effect',
  '107': 'The related or qualifying claim/service was not identified on this claim',
  '108': 'Rent/purchase guidelines were not met',
  '109': 'Claim/service not covered by this payer/contractor',
  '110': 'Billing date predates service date',
  '111': 'Not covered unless the provider accepts assignment',
  '112': 'Service not furnished directly to the patient and/or not documented',
  '113': 'Payment denied because service/equipment was furnished by a supplier and not authorized',
  '114': 'Procedure/product not approved by the Food and Drug Administration',
  '115': 'Procedure postponed, cancelled, or delayed',
  '116': 'The advance indemnification notice signed by the patient did not comply with requirements',
  '117': 'Transportation is only covered to the closest facility that can provide the necessary care',
  '118': 'Benefit is suspended pending the receipt of requested information',
  '119': 'Benefit maximum for this time period or occurrence has been reached',
  '120': 'Patient is covered by a managed care plan',
  '121': 'Indemnification adjustment',

  // Medicare-specific codes
  '128': 'Newborn\'s services are covered in the mother\'s allowance',
  '129': 'Prior processing information appears incorrect',
  '130': 'Claim submission fee',
  '131': 'Claim specific negotiated discount',
  '132': 'Prearranged demonstration project adjustment',
  '133': 'The disposition of this claim/service is pending further review',
  '134': 'Technical fees removed from charges',
  '135': 'Interim bill',
  '136': 'Failure to follow preadmission testing guidelines',
  '137': 'Regulatory surcharges, assessments, allowances or health-related taxes',
  '138': 'Appeal procedures not followed or time limits not met',
  '139': 'Contracted funding agreement',
  '140': 'Patient/Insured health identification number and name do not match',
  '141': 'Claim spans eligible and ineligible periods of coverage',
  '142': 'Monthly Medicaid patient liability amount',
  '143': 'Portion of payment deferred',
  '144': 'Incentive adjustment',
  '145': 'Premium payment withholding',
  '146': 'Diagnosis was invalid for the date(s) of service reported',
  '147': 'Provider contracted/negotiated rate expired or not on file',
  '148': 'Information from another provider was not provided or was insufficient/incomplete',
  '149': 'Lifetime benefit maximum has been reached for this service/benefit category',
  '150': 'Payment adjusted because the payer deems the information submitted does not support this many/frequency of services',

  // Newer codes
  '151': 'Payment denied/reduced because the payer deems the information submitted does not support this length of service',
  '152': 'Payment denied/reduced because the payer deems the information submitted does not support this dosage',
  '153': 'Payment denied/reduced because the payer deems the information submitted does not support this day\'s supply',
  '154': 'Payment denied/reduced because the payer deems the information submitted does not support this level of service',
  '155': 'Patient refused the service/procedure',
  '156': 'Flexible spending account payments',
  '157': 'Service/procedure was provided as a result of an act of war',
  '158': 'Service/procedure was provided outside United States or as a result of war',
  '159': 'Service/procedure was provided as a result of terrorism',
  '160': 'Injury/illness was the result of an activity that is a benefit exclusion',
  '161': 'Provider performance bonus',
  '162': 'State-mandated Requirement for Property and Casualty',
  '163': 'Attachment/other documentation referenced on the claim was not received',
  '164': 'Attachment/other documentation referenced on the claim was not received in a timely fashion',
  '165': 'Referral absent or exceeded',
  '166': 'These services were submitted after this payers responsibility for processing claims under this plan ended',
  '167': 'This (these) diagnosis(es) is (are) not covered',
  '168': 'Service(s) have been considered under the patient\'s medical plan',
  '169': 'Alternate benefit has been provided',
  '170': 'Payment is denied when performed/billed by this type of provider',
  '171': 'Payment is denied when performed/billed by this type of provider in this type of facility',
  '172': 'Payment is adjusted when performed/billed by a provider of this specialty',
  '173': 'Service/equipment was not prescribed by a physician',
  '174': 'Service was not prescribed prior to delivery',
  '175': 'Prescription is incomplete',
  '176': 'Prescription is not current',
  '177': 'Patient has not met the required eligibility requirements',
  '178': 'Patient has not met the required spend down requirements',
  '179': 'Patient has not met the required waiting requirements',
  '180': 'Patient has not met the required residency requirements',
  '181': 'Procedure code was invalid on the date of service',
  '182': 'Procedure modifier was invalid on the date of service',
  '183': 'The referring provider is not eligible to refer the service billed',
  '184': 'The prescribing/ordering provider is not eligible to prescribe/order the service billed',
  '185': 'The rendering provider is not eligible to perform the service billed',
  '186': 'Level of care change adjustment',
  '187': 'Consumer directed/managed care arrangement',
  '188': 'This product/procedure is only covered when used according to FDA recommendations',
  '189': 'Not otherwise classified (NOC) or unlisted procedure code',
  '190': 'Payment is included in the allowance for a Skilled Nursing Facility (SNF) comprehensive care',
  '191': 'Not a member/subscriber/covered party',
  '192': 'Non-standard adjustment code from paper remittance advice',
  '193': 'Original payment decision is being maintained',
  '194': 'Anesthesia performed by the operating physician',
  '195': 'Refund issued to an insured/subscriber/patient',
  '196': 'Claim/service denied based on prior payer\'s coverage determination',
  '197': 'Precertification/authorization/notification absent',
  '198': 'Precertification/authorization exceeded',
  '199': 'Revenue code and procedure code do not match',
  '200': 'Expenses incurred during lapse in coverage',
  '201': 'Workers\' Compensation case settled. Patient is responsible',
  '202': 'Non-covered personal comfort or convenience services',
  '203': 'Discontinued or reduced service',
  '204': 'Service not payable per managed care contract',
  '205': 'Pharmacy discount card processing fee',
  '206': 'National Provider Identifier - not provided',
  '207': 'National Provider Identifier - not valid',
  '208': 'National Provider Identifier - not matched',
  '209': 'Per regulatory requirement, payment based on current approved level of care',

  // Recent additions
  '226': 'Information requested from the Billing/Rendering Provider was not provided',
  '227': 'Information requested from the patient/insured/responsible party was not provided',
  '228': 'Denied for failure of this provider, another provider or spouse to repay',
  '229': 'Partial charge amount not considered by Medicare due to MSP cost-avoiding payer',
  '230': 'Claim not submitted as required by participating provider agreement',
  '231': 'Mutually exclusive procedures cannot be done in same day/setting',
  '232': 'Institutional and professional charges should be billed separately',
  '233': 'Services/charges related to the treatment of non-covered condition',
  '234': 'This procedure is not paid separately',
  '235': 'Sales tax',
  '236': 'This procedure or procedure/modifier combination is not compatible with another procedure',
  '237': 'Legislated/Regulatory penalty',
  '238': 'Claim spans ineligible and eligible periods of coverage',
  '239': 'Claim spans benefit limitation of coverage',
  '240': 'The diagnosis is inconsistent with the procedure',
  '241': 'Low income subsidy (LIS) co-payment amount',
  '242': 'Services not provided by network/primary care providers',
  '243': 'Services not authorized by network/primary care providers',
  '244': 'Payment is adjusted when performed by this type of qualified health professional',
  '245': 'Provider performance program withhold',
  '246': 'This non-payable code is for state reporting/informational purposes only',
  '247': 'Deductible for Health Savings Account or Archer Medical Savings Account',
  '248': 'Payment reflects the lesser of the provider\'s charges or network fee schedule',
  '249': 'This claim has been identified as a readmission',
  '250': 'The attachment sent does not meet payer requirements',
  '251': 'The attachment request was not processed due to a payer system error',
  '252': 'An attachment is required for adjudication',
  '253': 'Sequestration - Loss of Medicare payment',
  '254': 'Claim received by the dental plan',
  '255': 'Plan enrollment changes',
  '256': 'Service not payable per managed care contract',
  '257': 'The certificate of medical necessity is not on file',
  '258': 'Claim received by Medicare',
  '259': 'Additional payment for provider qualifying quality reporting',
  '260': 'Non-participating, no agreement to accept balance as payment in full',
};

/**
 * Remittance Advice Remark Codes (RARC)
 *
 * Supplementary codes that provide additional explanation
 * for claim adjustments. Used in conjunction with CARC codes.
 */
export const RARC_CODES: Record<string, string> = {
  // Common remark codes (M-series for Medicare)
  M1: 'X-ray not taken within the past 12 months or near enough to the start of treatment',
  M2: 'Not paid separately when the patient is an inpatient',
  M3: 'Equipment is the same or similar to equipment already being used',
  M4: 'Alert: This is the 10th month rental',
  M5: 'An oxygen saturation test is required prior to initial certification',
  M6: 'Alert: You must furnish and service this item for any period of medical need',
  M7: 'No rental payments after purchase elections',
  M8: 'We do not accept claims for this supplier category',
  M9: 'Alert: This claim requires an invoice',
  M10: 'Alert: Payment based on the lower of submitted charges or fee schedule',
  M11: 'DME, orthotics and prosthetics (DMEPOS) fee schedule has been updated',
  M12: 'Please review for accuracy before accepting',
  M13: 'Only one initial visit is covered per specialty per medical group',
  M14: 'No separate payment for services rendered',
  M15: 'Separately billed services/tests have been bundled',
  M16: 'Please see your primary care physician',
  M17: 'We are the primary payer',
  M18: 'Allowance based on the rate for a non-physician service',
  M19: 'Missing/incomplete/invalid oxygen certification/re-certification',
  M20: 'Missing/incomplete/invalid HCPCS modifier',
  M21: 'Missing/incomplete/invalid itemized statement or procedure information',
  M22: 'Missing/incomplete/invalid level of subluxation',
  M23: 'Missing/incomplete/invalid original claim data for a rebill',
  M24: 'Missing/incomplete/invalid number of treatments projected',
  M25: 'Missing/incomplete/invalid patient health questionnaire (PHQ)',
  M26: 'Missing/incomplete/invalid PCP service authorization',
  M27: 'Missing/incomplete/invalid medical record information',
  M28: 'This does not qualify for a skilled nursing facility',
  M29: 'Missing/incomplete/invalid mental status exam',
  M30: 'Missing/incomplete/invalid name or relationship of the referring physician',
  M31: 'Missing/incomplete/invalid operative note',
  M32: 'Missing/incomplete/invalid pathology report',
  M33: 'Missing/incomplete/invalid prior authorization number',
  M34: 'Missing/incomplete/invalid procedure code(s) for related claim(s)',
  M35: 'Missing/incomplete/invalid provider tax identification number',
  M36: 'Missing/incomplete/invalid referring and/or attending physician UPIN',
  M37: 'Missing/incomplete/invalid service facility name/address',
  M38: 'Missing/incomplete/invalid service or place of service',
  M39: 'Missing/incomplete/invalid servicing provider primary identifier',
  M40: 'Missing/incomplete/invalid x-ray certification/re-certification',

  // N-series codes
  N1: 'Alert: You may appeal this decision',
  N2: 'Alert: Additional information/explanation is available',
  N3: 'Missing/incomplete/invalid procedure report',
  N4: 'Missing/incomplete/invalid modifier for procedure code',
  N5: 'Alert: Under your contract, all claims must be submitted electronically',
  N6: 'Under state law, certain specified services are covered within limits',
  N7: 'Missing/incomplete/invalid treatment number',
  N8: 'Missing/incomplete/invalid date of birth',
  N9: 'Claim is being processed through a different claim system',
  N10: 'Payment based on a predetermined covered amount',
  N11: 'Resubmit this claim to the primary payer',
  N12: 'Claim has been processed per the state fee schedule',
  N13: 'Payment based on professional/technical component billing guidelines',
  N14: 'Missing/incomplete/invalid prior insurance carrier EOB',
  N15: 'Missing/incomplete/invalid referring provider identifier',
  N16: 'Missing/incomplete/invalid original claim reference number',

  // MA-series codes
  MA01: 'Alert: If you do not agree with what we approved for these services, you may appeal',
  MA02: 'Alert: If you do not agree with the adjustment, please contact us',
  MA03: 'Missing/incomplete/invalid signature of patient or representative',
  MA04: 'Secondary payment cannot be calculated without a primary EOB',
  MA05: 'Services were not furnished to a patient of the institution',
  MA06: 'Patient was not covered during all or part of the period',
  MA07: 'Missing/incomplete/invalid Claim Information Reporting Code',
  MA08: 'Alert: Information is being sent concerning a Medicare Secondary Payer',
  MA09: 'Alert: Medicare Advantage enrollees who have appealed decisions on their Part D claim',
  MA10: 'Alert: The patient may appeal if not in agreement with Medicare\'s determination',
  MA11: 'Missing/incomplete/invalid rendering provider signature',
  MA12: 'Missing/incomplete/invalid patient signature',
  MA13: 'Alert: You may be subject to penalties if you bill the patient for amounts',
  MA14: 'Alert: The patient is a member of an employer-sponsored prepaid health plan',
  MA15: 'Missing/incomplete/invalid authorization number for this service',
  MA18: 'Alert: The claim information has been forwarded to the Patient\'s drug plan',
  MA19: 'Alert: Information was already on file for this patient',
  MA20: 'Skilled nursing facility (SNF) pay rate for RUG classifications',
  MA21: 'Alert: This claim has been forwarded to the patient\'s other insurer',
  MA22: 'Alert: The patient is responsible for any denied or reduced services',
  MA23: 'Alert: You have filed a duplicate claim',
  MA24: 'The number of days or units billed exceeds plan maximums',
  MA25: 'A unit of service is defined differently than on original submission',
  MA26: 'Missing/incomplete/invalid number of services',
  MA27: 'Missing/incomplete/invalid nature of patient\'s condition',
  MA28: 'Missing/incomplete/invalid patient diagnosis or prognosis',
  MA29: 'Missing/incomplete/invalid patient\'s history',
  MA30: 'Missing/incomplete/invalid patient\'s initial evaluation',

  // Common RARC for denials
  N20: 'Service not covered when patient is enrolled in a hospice',
  N21: 'Alert: Your line item has been separated into multiple lines',
  N22: 'This procedure code was added/changed because it is required by the Federal law',
  N23: 'Alert: This service was processed as a result of a compliance review',
  N24: 'Missing/incomplete/invalid Electronic Funds Transfer (EFT) information',
  N25: 'Alert: This policy was processed as a duplicate',
  N26: 'Alert: Missing/incomplete/invalid accident questionnaire',
  N27: 'Missing/incomplete/invalid treatment authorization code',
  N28: 'Alert: This patient is not covered under this policy',
  N29: 'Missing/incomplete/invalid documentation',
  N30: 'Patient ineligible for this service',

  // Recent additions
  N700: 'Alert: No appeal rights',
  N701: 'A pattern of claims for this service has been detected',
  N702: 'Alert: An evaluation and management (E&M) code was billed',
  N703: 'Alert: This is a required field',
  N704: 'Alert: This claim has been corrected',
  N705: 'Alert: This claim was not processed',
  N706: 'Alert: The diagnosis code(s) were changed',
  N707: 'Alert: The CPT/HCPCS code has been changed',
  N708: 'Alert: The service was unrelated to the original condition',
  N709: 'Alert: This claim contains services that are subject to an audit',
  N710: 'Alert: The prior authorization was not obtained for this service',
};

/**
 * Common denial reason categories for analytics
 */
export const DENIAL_CATEGORIES: Record<string, string[]> = {
  ELIGIBILITY: ['31', '32', '177', '178', '180', '191', '200', '238'],
  AUTHORIZATION: ['15', '38', '39', '62', '165', '197', '198'],
  MEDICAL_NECESSITY: ['50', '55', '56', '57'],
  CODING: ['4', '5', '6', '7', '8', '9', '10', '11', '12', '16', '181', '182', '240'],
  DUPLICATE: ['18', 'E3'],
  TIMELY_FILING: ['29', '52'],
  BUNDLING: ['59', '97', '234', '236'],
  COORDINATION_OF_BENEFITS: ['22', '23'],
  NON_COVERED: ['49', '96', '109', '167', '202'],
  MISSING_INFO: ['17', '148', '163', '164', '226', '227'],
};

export default {
  CARC_CODES,
  RARC_CODES,
  DENIAL_CATEGORIES,
};
